siteName: Portfolio - Meriton Askaj
productionUrl: https://poko-website-builder-79u.pages.dev/
languages:
  - code: fr
    name: Fran√ßais
    customUrlPrefix: null
    status: published
    isCmsDefault: false
    isWebsiteDefault: false
